In [4]:
import pandas as pd
from cif import cif
import math
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.api as sm

In [10]:
import pandas as pd

ocde_df = pd.read_csv(r"https://raw.githubusercontent.com/Adrien-Mcode/Stat-app-Trumpnomics/main/Tableaux_csv/ocde2.csv?token=ASA6PWS5PTEWMDRZ6IZEGZLAGPJR4")

ocde_df.rename(columns={'Unnamed: 0':'Variables'}, inplace=True)

ind_tuple = list(zip(ocde_df['Pays'], ocde_df['Variables']))
new_index = pd.MultiIndex.from_tuples(ind_tuple, names=["Pays", "Variables"])

tocde = ocde_df.T.copy()
tocde.columns = new_index
tocde.drop(['Variables', 'Pays'], inplace=True)

In [11]:
import csv
bottom_50 = pd.read_csv(r"https://raw.githubusercontent.com/Adrien-Mcode/Stat-app-Trumpnomics/main/bottom_50_income.csv?token=ASA6PWQ4LLMILRV2KBTORWTAGPJUY",
                       header = 1,
                       sep=';')

In [12]:
import csv
top_10 =pd.read_csv(r"https://raw.githubusercontent.com/Adrien-Mcode/Stat-app-Trumpnomics/main/top_10_income.csv?token=ASA6PWRGHWTR5PVLLXYCYULAGPJXQ",
                   header = 1,
                   sep=';')

In [14]:
df_ocde = pd.read_csv(r"https://raw.githubusercontent.com/Adrien-Mcode/Stat-app-Trumpnomics/main/Tableaux_csv/ocde2.csv?token=ASA6PWUH4XFOYRJ57U3KZ73AGPJ6C")

In [15]:
import csv


pays_ocde = {"Germany" :'DEU',"Australia" :'AUS',"Austria":'AUT',"Belgium":'BEL',
             "Canada":'CAN',"Denmark":'DNK',"Spain":'ESP',"Finland":'FIN',
             "France":'FRA',"Greece":'GRC',"Ireland":'IRL',"Italy":'ITA',
             "Japan":'JPN',"Luxembourg":'LUX',"Norway":'NOR',"New-Zealand":'NZL',
             "Netherlands":'NLD',"Portugal":'PRT',"United Kingdom":'GBR',
             "Sweden":'SWE',"Switzerland":'CHE',"Turkey":'TUR',"United-States":'USA'}



df_ocde.rename(columns={'Unnamed: 0':'Variables'}, inplace=True)

ind_tuple = list(zip(df_ocde['Pays'], df_ocde['Variables']))
new_index = pd.MultiIndex.from_tuples(ind_tuple, names=["Pays", "Variables"])
#mise en place du système de double indice
tocde = df_ocde.T.copy()
tocde.columns = new_index
tocde.drop(['Variables', 'Pays'], inplace=True)
#tocde = tocde.drop(['2020-Q1','2020-Q2','2020-Q3','2020-Q4','2021-Q1'])
#renommage des colonnes de bottom_50 et top_10
bottom_50.columns = ['Variables', 'Year'] + sorted(pays_ocde.keys(), key=str)
top_10.columns = ['Variables', 'Year'] + sorted(pays_ocde.keys(), key=str)

#on prépare bottom_50 pour la fusion
bottom_50 = bottom_50.drop('Variables', axis=1)
for i in range (1,3) : 
    bottom_50 = pd.concat([bottom_50,bottom_50]) 
    
annee = []
for j in range (1,5):
    for i in range (0,29):
        annee.append(str(1991+i)+'-Q'+str(j))
bottom_50['Year'] = annee

#Mise en place double index pour bottom_50 :
bottom_50 = bottom_50.set_index('Year')

bottom_50['Variables'] = 'income p0p50'

ind_tuple = list(zip(bottom_50.columns, bottom_50['Variables']))

new_index = pd.MultiIndex.from_tuples(ind_tuple, names=["Pays", "Variables"])

bottom_50.columns = new_index

bottom_50 = bottom_50.drop(('Variables','income p0p50'), axis = 1)

tocde = tocde.merge(right=bottom_50, how='outer',
                    left_index=True,
                    right_index=True).sort_index(axis = 0).sort_index(axis = 1)

#on prépare top_10 pour la fusion :
top_10 = top_10.drop('Variables', axis = 1)
for i in range (1,3) : 
    top_10 = pd.concat([top_10,top_10])    
    
annee = []
for j in range (1,5):
    for i in range (0,29):
        annee.append(str(1991+i)+'-Q'+str(j))
top_10['Year'] = annee

#Mise en place double index pour top_10 :
top_10 = top_10.set_index('Year')

top_10['Variables'] = 'income p90p100'

ind_tuple = list(zip(top_10.columns, top_10['Variables']))

new_index = pd.MultiIndex.from_tuples(ind_tuple, names=["Pays", "Variables"])

top_10.columns = new_index

top_10 = top_10.drop(('Variables','income p90p100'), axis=1)

tocde = tocde.merge(right = top_10,
                    how='outer',
                    left_index=True,
                    right_index=True).sort_index(axis = 0).sort_index(axis = 1)

qs = tocde.index.str.replace(r'(Q\d) (\d+)', r'\2-\1')

tocde['date'] = pd.PeriodIndex(qs, freq='Q').to_timestamp()


tocde = tocde.reindex(index=tocde['date'])
tocde = tocde.drop("date", axis=1)

In [57]:
tocde

Pays            AUS                                                         \
Variables    Actifs  Chomage    Conso  Emplois  Exports Formation      PIB
date
1990-01-01  63.5595  6.23002  108.373  59.5996   26.942    41.272   206.89
1990-04-01  63.7865  6.46453  108.965  59.6628   26.986    39.657  207.173
1990-07-01  63.9287  7.22537  109.106  59.3098   28.052    39.505  205.931
1990-10-01  63.6977  7.86751  108.421  58.6863   28.496    38.098  207.139
1991-01-01  63.3995  8.73256  108.655  57.8632   29.718    36.525  204.453
...             ...      ...      ...      ...      ...       ...      ...
2018-10-01   65.629  5.03693  269.315  62.3233  116.359   113.548  486.394
2019-01-01  65.6701   5.0256   270.33  62.3697  117.741   112.894  488.812
2019-04-01  65.9566  5.22984  271.244  62.5071  119.861   111.682  491.985
2019-07-01  66.0785   5.2299  271.195  62.6227  120.854   112.746  494.974
2019-10-01  65.9389  5.16322  272.211  62.5343  120.146   112.018  496.921

Pays            AUT                    ...      USA                    \
Variables    Actifs  Chomage    Conso  ...  Chomage    Conso  Emplois
date                                   ...
1990-01-01      NaN  3.15392      NaN  ...      5.3  5998.06     63.2
1990-04-01      NaN  3.26997      NaN  ...  5.33333  6016.33       63
1990-07-01      NaN  3.41228      NaN  ...      5.7  6040.16  62.6667
1990-10-01      NaN  3.23917      NaN  ...  6.13333  5994.21  62.3333
1991-01-01      NaN  3.38382      NaN  ...      6.6  5971.67     61.9
...             ...      ...      ...  ...      ...      ...      ...
2018-10-01  61.4248  4.77307  47.4263  ...  3.83333  13033.4     60.5
2019-01-01  61.5643  4.76479  48.1421  ...  3.86667  13093.2     60.7
2019-04-01  61.4554  4.47055  47.8964  ...  3.66667  13212.8  60.6333
2019-07-01  61.2008  4.37813  47.7142  ...      3.6  13301.3  60.8333
2019-10-01  61.2359  4.33111  47.5393  ...      3.6  13353.7  60.9667

Pays                                   United Kingdom                 \
Variables   Exports Formation      PIB   income p0p50 income p90p100
date
1990-01-01    682.3   1695.37  9358.29            NaN            NaN
1990-04-01  690.785   1668.44  9392.25            NaN            NaN
1990-07-01  696.014   1659.14   9398.5            NaN            NaN
1990-10-01  702.143   1628.39  9312.94            NaN            NaN
1991-01-01  706.434   1587.41  9269.37         0.2823         0.2593
...             ...       ...      ...            ...            ...
2018-10-01  2548.79   3983.12  18813.9         0.2559         0.2894
2019-01-01  2560.41   4020.35  18950.3         0.2564         0.2884
2019-04-01  2531.42   4029.71  19020.6         0.2564         0.2884
2019-07-01  2536.56   4054.51  19141.7         0.2564         0.2884
2019-10-01  2557.85    4075.4    19254         0.2564         0.2884

Pays       United-States
Variables   income p0p50 income p90p100
date
1990-01-01           NaN            NaN
1990-04-01           NaN            NaN
1990-07-01           NaN            NaN
1990-10-01           NaN            NaN
1991-01-01        0.2496         0.2931
...                  ...            ...
2018-10-01        0.2368         0.3187
2019-01-01        0.2367         0.3187
2019-04-01        0.2367         0.3187
2019-07-01        0.2367         0.3187
2019-10-01        0.2367         0.3187

[120 rows x 207 columns]

In [96]:
from statsmodels.tsa.stattools import kpss
def kpss_test(series, **kw):    
    statistic, p_value, n_lags, critical_values = kpss(series, **kw)
    return(p_value)

In [114]:
def kpss_test_int(serie1):
    serie2 = serie1 - serie1.shift().fillna(0)
    serie2.drop(pd.Timestamp('1990-01-01 00:00:00'), inplace=True)
    kpss_test(serie2)
    return(p_value)

In [115]:
serie1=tocde['USA']['PIB']
kpss_test(serie1)
kpss_test_int(serie1)

C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)

0.01

In [65]:
pays = []
for x in pays_ocde:
    pays.append(pays_ocde[x])
print(len(pays))  
variables = ['Actifs',"Chomage","Conso","Emplois","Exports","Formation","PIB"]
print(len(variables))

23
7

In [71]:
tabkpss=pd.DataFrame(index= variables, columns=pays)
tabkpss

,DEU,AUS,AUT,BEL,CAN,DNK,ESP,FIN,FRA,GRC,...,LUX,NOR,NZL,NLD,PRT,GBR,SWE,CHE,TUR,USA
Actifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Chomage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Conso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Emplois,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Exports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Formation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PIB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
for a in pays: 
    for b in variables: 
        serie1=tocde[a][b]
        g=kpss_test(serie1)
        print(g)
        if g > 0.05:
            tabkpss[a][b]=kpss_test(serie1)
        else :
            tabkpss[a][b]=kpss_test_int(serie1)

nan
0.05121854683679288
nan
nan
nan
nan
nan
0.01
0.016580309927596282
0.01
0.01
0.01
0.01
0.01
nan
0.01198170846838955
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
0.016777620559500765
0.01
nan
0.01

C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)

0.01
0.01
nan
0.1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
0.01
nan
0.01
0.01

C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)

0.01
nan
nan
0.01
nan
0.01
0.01
0.01
nan
0.022158719040140926
nan
nan
nan
nan
nan
nan
0.1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
0.010770813224981031
0.1
nan
0.020527932886410707
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
0.01
nan
0.01
0.01
0.01

C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)

0.01
0.025323064264568814
0.01
0.01
0.01
0.01
0.01
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)

0.01
0.01
0.01
nan
nan
nan
nan
nan
nan
nan
nan
nan
0.01
nan
0.01
0.01
0.01
nan
nan
nan
nan
nan
nan
nan
0.01
0.1
0.01
0.027617608676469594
0.01
0.01
0.01

C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
C:\Users\duran\anaconda3\lib\site-packages\statsmodels\tsa\stattools.py:1687: InterpolationWarning: p-value is greater than the indicated p-value
  warn("p-value is greater than the indicated p-value", InterpolationWarning)

In [117]:
tabkpss

,DEU,AUS,AUT,BEL,CAN,DNK,ESP,FIN,FRA,GRC,...,LUX,NOR,NZL,NLD,PRT,GBR,SWE,CHE,TUR,USA
Actifs,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
Chomage,0.0512185,0.01,0.01,0.01,0.01,0.1,0.01,0.01,0.01,0.01,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.1
Conso,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
Emplois,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
Exports,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
Formation,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
PIB,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01

In [138]:
tabadf=pd.DataFrame(index= variables, columns=pays)

In [125]:
from statsmodels.tsa.stattools import adfuller
def adf_test(series, **kw):    
    statistic, p_value, n_lags, nobs, critical_values, icbest = adfuller(series, **kw)
    return(p_value)

In [139]:
def adf_test_int(serie1):
    serie2 = serie1 - serie1.shift().fillna(0)
    #serie2.drop(pd.Timestamp('1990-01-01 00:00:00'), inplace=True)
    serie2.dropna(inplace=True)
    adf_test(serie2)
    return(p_value)

In [140]:
for a in pays: 
    for b in variables: 
        serie1=tocde[a][b]
        serie1.dropna(inplace=True)
        print(serie1)
        g=adf_test(serie1)
        print(g)
        if g > 0.05:
            tabadf[a][b]=adf_test(serie1)
        else :
            tabadf[a][b]=adf_test_int(serie1)

C:\Users\duran\anaconda3\lib\site-packages\pandas\core\series.py:4494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(result)

date
2005-01-01    58.3072
2005-04-01    58.3661
2005-07-01    58.4698
2005-10-01    58.5227
2006-01-01    58.8413
2006-04-01    58.9132
2006-07-01    58.9684
2006-10-01    59.1055
2007-01-01    58.9413
2007-04-01    59.1698
2007-07-01    59.2552
2007-10-01    59.2305
2008-01-01    59.1794
2008-04-01    59.0434
2008-07-01    59.4233
2008-10-01     59.302
2009-01-01    59.2839
2009-04-01    59.3375
2009-07-01    59.2242
2009-10-01    59.7224
2010-01-01    59.3555
2010-04-01    59.3409
2010-07-01    59.3383
2010-10-01    59.4446
2011-01-01    59.7482
2011-04-01    60.1734
2011-07-01    60.2132
2011-10-01    60.2258
2012-01-01    59.9289
2012-04-01    60.0419
2012-07-01     60.166
2012-10-01    60.1317
2013-01-01    60.2814
2013-04-01    60.4514
2013-07-01    60.3384
2013-10-01    60.3401
2014-01-01    60.3432
2014-04-01    60.4128
2014-07-01    60.4822
2014-10-01    60.3929
2015-01-01    60.0481
2015-04-01    60.0996
2015-07-01    60.1088
2015-10-01    60.4189
2016-01-01    60.9253
2016-04-01    60.8906
2016-07-01    61.0909
2016-10-01    61.1235
2017-01-01    61.0361
2017-04-01      61.15
2017-07-01    61.3235
2017-10-01    61.3294
2018-01-01    61.1837
2018-04-01    61.1795
2018-07-01    61.3504
2018-10-01    61.4185
2019-01-01    61.6526
2019-04-01    61.7954
2019-07-01    61.9263
2019-10-01    62.2827
Name: Actifs, dtype: object
0.9573091291825104
date
1990-01-01    5.05985
1990-04-01    4.91484
1990-07-01    4.71423
1990-10-01    4.57733
1991-01-01    5.20503
               ...
2018-10-01      3.281
2019-01-01    3.16517
2019-04-01    3.08081
2019-07-01    3.12489
2019-10-01    3.18523
Name: Chomage, Length: 120, dtype: object
0.8678202315998853
date
1991-01-01    314.052
1991-04-01    317.298
1991-07-01    311.487
1991-10-01    317.819
1992-01-01    321.205
               ...
2018-10-01    425.819
2019-01-01    429.636
2019-04-01    429.516
2019-07-01    430.678
2019-10-01    430.918
Name: Conso, Length: 116, dtype: object
0.9872636331955044
date
2005-01-01    51.9901
2005-04-01    51.7731
2005-07-01    51.8394
2005-10-01    51.9708
2006-01-01    52.4845
2006-04-01    52.8139
2006-07-01     53.092
2006-10-01     53.265
2007-01-01    53.5839
2007-04-01    54.0082
2007-07-01    54.2014
2007-10-01    54.3175
2008-01-01    54.5592
2008-04-01    54.4562
2008-07-01    55.0954
2008-10-01    55.0071
2009-01-01    54.7585
2009-04-01    54.7099
2009-07-01    54.4951
2009-10-01    55.2124
2010-01-01    54.9218
2010-04-01    55.1549
2010-07-01     55.347
2010-10-01    55.5131
2011-01-01    56.0513
2011-04-01    56.6307
2011-07-01    56.7479
2011-10-01    56.9311
2012-01-01    56.6579
2012-04-01    56.8137
2012-07-01    56.9397
2012-10-01    56.9322
2013-01-01    57.0602
2013-04-01    57.2673
2013-07-01    57.2109
2013-10-01    57.2454
2014-01-01    57.2668
2014-04-01    57.4123
2014-07-01    57.4802
2014-10-01    57.4368
2015-01-01    57.2112
2015-04-01    57.2714
2015-07-01    57.4029
2015-10-01    57.6608
2016-01-01    58.3002
2016-04-01    58.3303
2016-07-01    58.5903
2016-10-01    58.7511
2017-01-01    58.6569
2017-04-01    58.8476
2017-07-01    59.0583
2017-10-01    59.1059
2018-01-01    59.0711
2018-04-01    59.0649
2018-07-01    59.2988
2018-10-01    59.4034
2019-01-01    59.7012
2019-04-01    59.8916
2019-07-01    59.9912
2019-10-01    60.2988
Name: Emplois, dtype: object
0.7965132863843041
date
1991-01-01    108.561
1991-04-01    102.206
1991-07-01    107.212
1991-10-01    107.496
1992-01-01    108.587
               ...
2018-10-01    391.255
2019-01-01    397.396
2019-04-01    391.149
2019-07-01    396.047
2019-10-01    394.947
Name: Exports, Length: 116, dtype: object
0.9440056050986796
date
1991-01-01    121.031
1991-04-01    122.288
1991-07-01     123.03
1991-10-01    126.347
1992-01-01    130.088
               ...
2018-10-01    169.846
2019-01-01    172.334
2019-04-01    171.698
2019-07-01    171.592
2019-10-01    171.183
Name: Formation, Length: 116, dtype: object
0.9552881299857835
date
1991-01-01    557.347
1991-04-01    554.396
1991-07-01    553.261
1991-10-01    560.449
1992-01-01    568.903
               ...
2018-10-01    806.326
2019-01-01    811.262
2019-04-01    807.177
2019-07-01    809.673
2019-10-01    809.522
Name: PIB, Length: 116, dtype: object
0.930255163382589
date
1990-01-01    63.5595
1990-04-01    63.7865
1990-07-01    63.9287
1990-10-01    63.6977
1991-01-01    63.3995
               ...
2018-10-01     65.629
2019-01-01    65.6701
2019-04-01    65.9566
2019-07-01    66.0785
2019-10-01    65.9389
Name: Actifs, Length: 120, dtype: object
0.9118983036940589
date
1990-01-01    6.23002
1990-04-01    6.46453
1990-07-01    7.22537
1990-10-01    7.86751
1991-01-01    8.73256
               ...
2018-10-01    5.03693
2019-01-01     5.0256
2019-04-01    5.22984
2019-07-01     5.2299
2019-10-01    5.16322
Name: Chomage, Length: 120, dtype: object
0.5940984518790425
date
1990-01-01    108.373
1990-04-01    108.965
1990-07-01    109.106
1990-10-01    108.421
1991-01-01    108.655
               ...
2018-10-01    269.315
2019-01-01     270.33
2019-04-01    271.244
2019-07-01    271.195
2019-10-01    272.211
Name: Conso, Length: 120, dtype: object
0.9459370073240722
date
1990-01-01    59.5996
1990-04-01    59.6628
1990-07-01    59.3098
1990-10-01    58.6863
1991-01-01    57.8632
               ...
2018-10-01    62.3233
2019-01-01    62.3697
2019-04-01    62.5071
2019-07-01    62.6227
2019-10-01    62.5343
Name: Emplois, Length: 120, dtype: object
0.7838128818637846
date
1990-01-01     26.942
1990-04-01     26.986
1990-07-01     28.052
1990-10-01     28.496
1991-01-01     29.718
               ...
2018-10-01    116.359
2019-01-01    117.741
2019-04-01    119.861
2019-07-01    120.854
2019-10-01    120.146
Name: Exports, Length: 120, dtype: object
0.9975882912219615
date
1990-01-01     41.272
1990-04-01     39.657
1990-07-01     39.505
1990-10-01     38.098
1991-01-01     36.525
               ...
2018-10-01    113.548
2019-01-01    112.894
2019-04-01    111.682
2019-07-01    112.746
2019-10-01    112.018
Name: Formation, Length: 120, dtype: object
0.8563519348783883
date
1990-01-01     206.89
1990-04-01    207.173
1990-07-01    205.931
1990-10-01    207.139
1991-01-01    204.453
               ...
2018-10-01    486.394
2019-01-01    488.812
2019-04-01    491.985
2019-07-01    494.974
2019-10-01    496.921
Name: PIB, Length: 120, dtype: object
0.9990285868314188
date
1999-01-01    58.9968
1999-04-01    58.7752
1999-07-01    58.7293
1999-10-01    58.6407
2000-01-01    58.7256
               ...
2018-10-01    61.4248
2019-01-01    61.5643
2019-04-01    61.4554
2019-07-01    61.2008
2019-10-01    61.2359
Name: Actifs, Length: 84, dtype: object
0.8020436195951915
date
1990-01-01    3.15392
1990-04-01    3.26997
1990-07-01    3.41228
1990-10-01    3.23917
1991-01-01    3.38382
               ...
2018-10-01    4.77307
2019-01-01    4.76479
2019-04-01    4.47055
2019-07-01    4.37813
2019-10-01    4.33111
Name: Chomage, Length: 120, dtype: object
0.15564851857218237
date
1995-01-01    33.8041
1995-04-01    33.8968
1995-07-01    34.1407
1995-10-01    34.4213
1996-01-01    34.8369
               ...
2018-10-01    47.4263
2019-01-01    48.1421
2019-04-01    47.8964
2019-07-01    47.7142
2019-10-01    47.5393
Name: Conso, Length: 100, dtype: object
0.513721524794086
date
1999-01-01    56.6913
1999-04-01    56.5485
1999-07-01    56.6295
1999-10-01    56.5027
2000-01-01    56.4194
               ...
2018-10-01    58.4929
2019-01-01    58.6309
2019-04-01     58.708
2019-07-01    58.5213
2019-10-01    58.5837
Name: Emplois, Length: 84, dtype: object
0.4948687023532272
date
1995-01-01    17.8267
1995-04-01    17.8517
1995-07-01    18.1683
1995-10-01    17.9068
1996-01-01     18.174
               ...
2018-10-01    52.8052
2019-01-01    54.2381
2019-04-01    53.4888
2019-07-01    53.6339
2019-10-01     53.507
Name: Exports, Length: 100, dtype: object
0.826146817559228
date
1995-01-01    14.7927
1995-04-01    14.9504
1995-07-01    15.0453
1995-10-01    15.2584
1996-01-01    15.4151
               ...
2018-10-01    22.5076
2019-01-01    23.0363
2019-04-01    23.1935
2019-07-01    22.9221
2019-10-01     22.433
Name: Formation, Length: 100, dtype: object
0.9632716380036488
date
1995-01-01    59.7237
1995-04-01    60.1901
1995-07-01    60.3308
1995-10-01    60.9251
1996-01-01    61.1603
               ...
2018-10-01    93.0183
2019-01-01    93.7627
2019-04-01    93.4646
2019-07-01    93.7535
2019-10-01    93.2508
Name: PIB, Length: 100, dtype: object
0.6923225178645883
date
1999-01-01    52.3123
1999-04-01    52.2416
1999-07-01    52.1216
1999-10-01    51.8605
2000-01-01    51.9049
               ...
2018-10-01    54.4115
2019-01-01    54.0648
2019-04-01    54.9056
2019-07-01    54.5217
2019-10-01    54.0701
Name: Actifs, Length: 84, dtype: object
0.6877139854471644
date
1999-01-01    9.01045
1999-04-01    9.07383
1999-07-01    8.31669
1999-10-01    7.84229
2000-01-01    7.24941
               ...
2018-10-01    5.66198
2019-01-01    5.55868
2019-04-01    5.50051
2019-07-01    5.22056
2019-10-01    5.15844
Name: Chomage, Length: 84, dtype: object
0.14257134207389022
date
1995-01-01    38.765
1995-04-01    39.086
1995-07-01     39.39
1995-10-01    39.642
1996-01-01    39.721
               ...
2018-10-01    56.606
2019-01-01    56.622
2019-04-01    56.968
2019-07-01    57.434
2019-10-01    57.792
Name: Conso, Length: 100, dtype: object
0.9834843206931883
date
1999-01-01    47.5987
1999-04-01    47.5013
1999-07-01    47.7868
1999-10-01    47.7935
2000-01-01    48.1421
               ...
2018-10-01    51.3308
2019-01-01    51.0595
2019-04-01    51.8855
2019-07-01    51.6754
2019-10-01    51.2809
Name: Emplois, Length: 84, dtype: object
0.8243596694369884
date
1995-01-01    39.124
1995-04-01    38.244
1995-07-01    37.647
1995-10-01    38.351
1996-01-01    39.243
               ...
2018-10-01    91.771
2019-01-01    91.968
2019-04-01    91.916
2019-07-01     92.07
2019-10-01    93.078
Name: Exports, Length: 100, dtype: object
0.827603609628037
date
1995-01-01    14.847
1995-04-01    15.095
1995-07-01    15.265
1995-10-01    15.258
1996-01-01    15.002
               ...
2018-10-01    26.815
2019-01-01    26.908
2019-04-01    26.931
2019-07-01    27.022
2019-10-01    27.172
Name: Formation, Length: 100, dtype: object
0.9271441444763664
date
1995-01-01     71.086
1995-04-01     71.385
1995-07-01     71.813
1995-10-01     71.961
1996-01-01     71.816
               ...
2018-10-01    110.154
2019-01-01    110.329
2019-04-01    110.673
2019-07-01    111.234
2019-10-01    111.912
Name: PIB, Length: 100, dtype: object
0.785721045901528
date
1995-01-01       65.1
1995-04-01    64.8333
1995-07-01    64.7333
1995-10-01       64.6
1996-01-01    64.7333
               ...
2018-10-01    65.4333
2019-01-01    65.7333
2019-04-01    65.7667
2019-07-01       65.7
2019-10-01    65.5667
Name: Actifs, Length: 100, dtype: object
0.4008421629698869
date
1990-01-01    7.63333
1990-04-01    7.66667
1990-07-01    8.16667
1990-10-01    9.13333
1991-01-01    10.1667
               ...
2018-10-01        5.7
2019-01-01    5.76667
2019-04-01    5.56667
2019-07-01    5.63333
2019-10-01        5.7
Name: Chomage, Length: 120, dtype: object
0.587547318639386
date
1990-01-01    140.901
1990-04-01    139.352
1990-07-01    139.433
1990-10-01    138.989
1991-01-01    136.221
               ...
2018-10-01    300.777
2019-01-01    302.492
2019-04-01    303.076
2019-07-01    304.775
2019-10-01    306.278
Name: Conso, Length: 120, dtype: object
0.9982111421649049
date
1995-01-01    58.8667
1995-04-01    58.6333
1995-07-01    58.6333
1995-10-01       58.6
1996-01-01       58.6
               ...
2018-10-01       61.7
2019-01-01    61.9333
2019-04-01       62.1
2019-07-01         62
2019-10-01    61.8333
Name: Emplois, Length: 100, dtype: object
0.1256703834246496
date
1990-01-01    59.4158
1990-04-01    61.5707
1990-07-01    61.2122
1990-10-01    59.5875
1991-01-01    58.3625
               ...
2018-10-01    167.865
2019-01-01    165.967
2019-04-01    171.005
2019-07-01    169.939
2019-10-01    168.108
Name: Exports, Length: 120, dtype: object
0.3113820669545251
date
1990-01-01     56.143
1990-04-01    54.7788
1990-07-01    53.2788
1990-10-01     51.371
1991-01-01    51.7927
               ...
2018-10-01     107.79
2019-01-01    110.236
2019-04-01    109.747
2019-07-01    111.846
2019-10-01    110.822
Name: Formation, Length: 120, dtype: object
0.8013657463087046
date
1990-01-01    275.468
1990-04-01    274.327
1990-07-01    272.387
1990-10-01    269.959
1991-01-01    266.106
               ...
2018-10-01    519.634
2019-01-01    520.093
2019-04-01    525.653
2019-07-01     528.03
2019-10-01    528.528
Name: PIB, Length: 120, dtype: object
0.9654819167257268
date
1999-01-01    65.9625
1999-04-01    65.9429
1999-07-01    66.2707
1999-10-01    65.7891
2000-01-01    65.7431
               ...
2018-10-01    62.0489
2019-01-01    62.1515
2019-04-01    62.2956
2019-07-01    62.4076
2019-10-01    62.6445
Name: Actifs, Length: 84, dtype: object
0.7303568449467351
date
1990-01-01    8.07938
1990-04-01    8.40923
1990-07-01    8.21164
1990-10-01    8.44195
1991-01-01    8.83926
               ...
2018-10-01    5.27526
2019-01-01    5.11768
2019-04-01    4.88026
2019-07-01    4.89887
2019-10-01    5.17763
Name: Chomage, Length: 120, dtype: object
0.4855951011833512
date
1995-01-01     171.77
1995-04-01    173.771
1995-07-01    174.654
1995-10-01    175.092
1996-01-01    177.427
               ...
2018-10-01    241.072
2019-01-01    245.408
2019-04-01    244.328
2019-07-01    244.221
2019-10-01    247.692
Name: Conso, Length: 100, dtype: object
0.9051798104917574
date
1999-01-01    62.4682
1999-04-01    62.4216
1999-07-01    62.4771
1999-10-01    61.8511
2000-01-01    62.4311
               ...
2018-10-01    58.7757
2019-01-01    58.9708
2019-04-01    59.2554
2019-07-01    59.3503
2019-10-01     59.401
Name: Emplois, Length: 84, dtype: object
0.6963206276541458
date
1995-01-01    123.721
1995-04-01    121.356
1995-07-01    120.784
1995-10-01    122.148
1996-01-01    125.905
               ...
2018-10-01    308.365
2019-01-01    311.491
2019-04-01    321.517
2019-07-01    323.192
2019-10-01    318.179
Name: Exports, Length: 100, dtype: object
0.879422088121609
date
1995-01-01    59.0318
1995-04-01    59.7663
1995-07-01    62.6628
1995-10-01     66.073
1996-01-01    59.8561
               ...
2018-10-01    109.703
2019-01-01    115.463
2019-04-01    115.104
2019-07-01    115.313
2019-10-01    115.754
Name: Formation, Length: 100, dtype: object
0.6164287896033529
date
1995-01-01     360.82
1995-04-01    359.788
1995-07-01    361.288
1995-10-01    363.932
1996-01-01    363.986
               ...
2018-10-01     528.74
2019-01-01    532.899
2019-04-01    538.474
2019-07-01    541.222
2019-10-01    541.305
Name: PIB, Length: 100, dtype: object
0.9559658961856141
date
1999-01-01    51.5226
1999-04-01     51.703
1999-07-01    52.0302
1999-10-01     52.395
2000-01-01    52.5786
               ...
2018-10-01    57.8432
2019-01-01    57.8533
2019-04-01    57.9183
2019-07-01    57.9024
2019-10-01    57.9926
Name: Actifs, Length: 84, dtype: object
0.006485416569941323
date
1999-01-01    16.3727
1999-04-01    15.8282
1999-07-01    15.5164
1999-10-01    15.1006
2000-01-01     14.442
               ...
2018-10-01    14.5589
2019-01-01    14.2333
2019-04-01    14.0632
2019-07-01    14.1575
2019-10-01    13.9642
Name: Chomage, Length: 84, dtype: object
0.5974202542793426
date
1995-01-01    110.155
1995-04-01    111.139
1995-07-01    111.439
1995-10-01    112.332
1996-01-01    112.393
               ...
2018-10-01    170.124
2019-01-01    170.838
2019-04-01    170.379
2019-07-01     171.72
2019-10-01     171.87
Name: Conso, Length: 100, dtype: object
0.3206258237160952
date
1999-01-01    43.0869
1999-04-01    43.5194
1999-07-01    43.9569
1999-10-01     44.483
2000-01-01    44.9852
               ...
2018-10-01    49.4218
2019-01-01    49.6189
2019-04-01    49.7732
2019-07-01    49.7048
2019-10-01    49.8944
Name: Emplois, Length: 84, dtype: object
0.1780477314473709
date
1995-01-01     35.032
1995-04-01     34.988
1995-07-01     35.984
1995-10-01     36.527
1996-01-01     37.843
               ...
2018-10-01    103.764
2019-01-01    104.036
2019-04-01    105.594
2019-07-01    105.778
2019-10-01    105.962
Name: Exports, Length: 100, dtype: object
0.8350510559940445
date
1995-01-01    35.105
1995-04-01    35.427
1995-07-01    35.479
1995-10-01    35.483
1996-01-01    35.766
               ...
2018-10-01    57.105
2019-01-01     57.77
2019-04-01    57.571
2019-07-01    58.186
2019-10-01    57.625
Name: Formation, Length: 100, dtype: object
0.20892303767303033
date
1995-01-01    177.507
1995-04-01    178.608
1995-07-01    179.329
1995-10-01    180.692
1996-01-01     181.76
               ...
2018-10-01    295.252
2019-01-01    296.794
2019-04-01    297.916
2019-07-01     298.97
2019-10-01     300.21
Name: PIB, Length: 100, dtype: object
0.5144962712812081
date
2000-01-01    61.1566
2000-04-01    61.4769
2000-07-01    61.6146
2000-10-01    61.3996
2001-01-01    61.4042
               ...
2018-10-01    59.3441
2019-01-01    59.3044
2019-04-01     59.404
2019-07-01    59.4698
2019-10-01    59.5217
Name: Actifs, Length: 80, dtype: object
0.48143323078531813
date
1998-01-01    11.4977
1998-04-01    11.6081
1998-07-01     11.593
1998-10-01    10.9637
1999-01-01    10.3721
               ...
2018-10-01    6.58956
2019-01-01    6.64115
2019-04-01    6.72919
2019-07-01    6.78678
2019-10-01    6.62761
Name: Chomage, Length: 88, dtype: object
0.04515795791926791
date
1990-01-01    16.671
1990-04-01    16.815
1990-07-01    16.595
1990-10-01     16.33
1991-01-01    16.143
               ...
2018-10-01    27.274
2019-01-01    27.309
2019-04-01    27.903
2019-07-01    27.623
2019-10-01    27.311
Name: Conso, Length: 120, dtype: object
0.9619186389677377
date
2000-01-01    54.7574
2000-04-01     55.429
2000-07-01    55.7265
2000-10-01    55.6544
2001-01-01    55.7419
               ...
2018-10-01    55.4336
2019-01-01    55.3659
2019-04-01    55.4066
2019-07-01    55.4337
2019-10-01    55.5769
Name: Emplois, Length: 80, dtype: object
0.18847662382236424
date
1990-01-01     5.382
1990-04-01     5.703
1990-07-01      5.42
1990-10-01     5.585
1991-01-01     4.992
               ...
2018-10-01    20.995
2019-01-01     22.72
2019-04-01    22.134
2019-07-01    22.639
2019-10-01    23.108
Name: Exports, Length: 120, dtype: object
0.8142603969837252
date
1990-01-01     9.459
1990-04-01     8.907
1990-07-01     8.596
1990-10-01     8.451
1991-01-01     7.925
               ...
2018-10-01    12.326
2019-01-01    12.125
2019-04-01    12.139
2019-07-01    11.855
2019-10-01    11.872
Name: Formation, Length: 120, dtype: object
0.7489174089578863
date
1990-01-01    32.137
1990-04-01    31.695
1990-07-01    31.023
1990-10-01    30.844
1991-01-01    30.224
               ...
2018-10-01    51.057
2019-01-01     51.21
2019-04-01    51.685
2019-07-01    51.578
2019-10-01    51.239
Name: PIB, Length: 120, dtype: object
0.8661036390116179
date
2003-01-01    56.4936
2003-04-01    56.2963
2003-07-01    56.2382
2003-10-01    56.2426
2004-01-01    56.3118
               ...
2018-10-01    55.5611
2019-01-01    55.4806
2019-04-01    55.4152
2019-07-01    55.0845
2019-10-01    55.3405
Name: Actifs, Length: 68, dtype: object
0.97933405995792
date
2003-01-01    7.93574
2003-04-01    8.09662
2003-07-01    8.01927
2003-10-01    8.34581
2004-01-01    8.52777
               ...
2018-10-01    8.76056
2019-01-01    8.75797
2019-04-01    8.45035
2019-07-01    8.43242
2019-10-01    8.13304
Name: Chomage, Length: 68, dtype: object
0.3586941930018869
date
1990-01-01    199.163
1990-04-01    199.633
1990-07-01    200.218
1990-10-01    201.407
1991-01-01    201.232
               ...
2018-10-01    309.854
2019-01-01    311.626
2019-04-01    313.015
2019-07-01    314.152
2019-10-01    314.849
Name: Conso, Length: 120, dtype: object
0.9269487978867391
date

In [141]:
tabadf

,DEU,AUS,AUT,BEL,CAN,DNK,ESP,FIN,FRA,GRC,...,LUX,NOR,NZL,NLD,PRT,GBR,SWE,CHE,TUR,USA
Actifs,0.957309,0.911898,0.802044,0.687714,0.400842,0.730357,0.01,0.481433,0.979334,0.261595,...,0.25209,0.90111,0.81727,0.0674563,0.687589,0.668656,0.999052,0.828706,0.316541,0.878361
Chomage,0.86782,0.594098,0.155649,0.142571,0.587547,0.485595,0.59742,0.01,0.358694,0.0896801,...,0.150091,0.116332,0.0816972,0.146009,0.329977,0.749878,0.0575101,0.152779,0.303758,0.185986
Conso,0.987264,0.945937,0.513722,0.983484,0.998211,0.90518,0.320626,0.961919,0.926949,0.16929,...,0.988985,0.977487,0.998133,0.141009,0.233702,0.283944,0.994994,0.997475,0.984028,0.881046
Emplois,0.796513,0.783813,0.494869,0.82436,0.12567,0.696321,0.178048,0.188477,0.579482,0.398945,...,0.249054,0.910097,0.514302,0.130607,0.51442,0.299408,0.988853,0.0500527,0.503028,0.396558
Exports,0.944006,0.997588,0.826147,0.827604,0.311382,0.879422,0.835051,0.81426,0.871773,0.673548,...,0.919539,0.0576988,0.91089,0.97856,0.994581,0.940328,0.730641,0.992629,0.996671,0.907503
Formation,0.955288,0.856352,0.963272,0.927144,0.801366,0.616429,0.208923,0.748917,0.934455,0.670505,...,0.711252,0.851724,0.987818,0.298225,0.30035,0.965095,0.867341,0.995305,0.799295,0.856548
PIB,0.930255,0.999029,0.692323,0.785721,0.965482,0.955966,0.514496,0.866104,0.836168,0.107681,...,0.894148,0.286167,0.994322,0.630159,0.267933,0.828849,0.870212,0.997334,0.997578,0.955922